### ISSUE TITLE
gradlew Permission Denied

### ISSUE THREAD

**Issue by nietxan** [TheJustRusik/snake-game-javafx#1]
Issue with gradlew script on linux. It's not a big deal just need to run this `chmod +x gradlew`. But there  are better solution
![Screenshot from 2023-12-26 19-47-51](https://github.com/TheJustRusik/snake-game-javafx/assets/100429046/47af4010-fa93-4a33-9e64-080ac8e84274)

**Comment by TheJustRusik** [comment]
Thanks for your response to the bug. Just fixed it🪲
